# Generated by Django 2.1.5 on 2019-01-11 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CosApplyAppidPassInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comId', models.IntegerField(unique=True)),
                ('com_description', models.CharField(max_length=256)),
                ('com_type', models.CharField(max_length=64)),
                ('com_image_dir', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'e_shop_commodity_info',
                'ordering': ['id'],
            },
        ),
    ]
