# Generated by Django 2.1.5 on 2019-01-11 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('our1eshop', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CosApplyAppidPassInfo',
            new_name='EshopCommodityInfo',
        ),
    ]
